// keyMapIcon = {
//   MetaLeft: 'command',
//   MetaRight: 'command',
//   ShiftLeft: 'shift',
//   ShiftRight: 'shift',
//   ControlLeft: 'control',
//   ControlRight: 'control',
//   AltLeft: 'option',
//   AltRight: 'option',
//   CapsLock: 'caps_lock',
//   Space: 'space',
//   Tab: 'tab',
//   Backspace: 'backspace',
//   Enter: 'return',
//   Return: 'return',
//   Delete: 'delete',
//   Insert: 'insert',
//   Home: 'home',
//   End: 'end',
//   PageUp: 'page_up',
//   PageDown: 'page_down',
//   Up: 'arrow_up',
//   Down: 'arrow_down',
//   Left: 'arrow_left',
//   Right: 'arrow_right',
//   PrintScreen: 'print_screen',
//   ScrollLock: 'scroll_lock',
//   Pause: 'pause_break',
//   VolumeMute: 'volume_mute',
//   VolumeDown: 'volume_down',
//   VolumeUp: 'volume_up',
//   BrightnessDown: 'brightness_down',
//   BrightnessUp: 'brightness_up',
//   Eject: 'eject',
//   Help: 'help',
//   Power: 'power',
// }
// list = [
//   'Escape',
//   'Backquote',
//   'Digit1',
//   'Minus',
//   'Equal',
//   'Backspace',
//   'KeyQ',
//   'BracketLeft',
//   'BracketRight',
//   'Backslash',
//   'CapsLock',
//   'ShiftLeft',
//   'Comma',
//   'Comma',
//   'Period',
//   'Slash',
//   'ShiftRight',
//   'ControlLeft',
//   'AltLeft',
//   'MetaLeft',
//   'Space',
//   'MetaRight',
//   'AltRight',
// ]

const code = [
  'Escape',
  'Backquote',
  'Digit1',
  'Minus',
  'Equal',
  'Backspace',
  'KeyQ',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'CapsLock',
  'Semicolon',
  'Quote',
  'ShiftLeft',
  'Comma',
  'Comma',
  'Period',
  'Slash',
  'ShiftRight',
  'ControlLeft',
  'AltLeft',
  'MetaLeft',
  'Space',
  'MetaRight',
  'AltRight',
]
const key = [
  'Escape',
  '`',
  '1',
  '-',
  '=',
  'Backspace',
  'q',
  '[',
  ']',
  '\\',
  'CapsLock',
  ';',
  "'",
  'Shift',
  'Unidentified',
  ',',
  '.',
  '/',
  'Shift',
  'Control',
  'Alt',
  'Meta',
  ' ',
  'Meta',
  'Alt',
]
const keyMapIcon = {}
// 把key和code对应起来添加到keyMapIcon中
for (let i = 0; i < code.length; i++) {
  keyMapIcon[code[i]] = key[i]
}
console.log(keyMapIcon)

ppp = {
  Backquote: '`',
  Digit0: '0',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  CapsLock: 'CapsLock',
  ShiftLeft: 'Shift',
  ShiftRight: 'Shift',
  ControlLeft: 'Control',
  AltLeft: 'Alt',
  MetaLeft: 'Meta',
  MetaRight: 'Meta',
  AltRight: 'Alt',
}
